### ISSUE TITLE
Steps to test the repo functionalities (OSOE-803)

### ISSUE THREAD

**Issue by hishamco** [Lombiq/Hosting-Tenants#110]
It would be nice if you added steps to test the various features in this repo

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-803)

**Comment by Piedone** [comment]
There are tests, see all the `*.Tests.UI` projects. Is there anything you're missing in particular?

**Comment by hishamco** [comment]
So you rely heavily on the UI tests. I assume there's a web host that anyone can try out the features without touching the tests. IMHO the tests could only used for testing use cases

**Comment by Piedone** [comment]
I don't really understand. The tests are indeed for testing :). Isn't this what your issue is about? If you mean documentation about how to use these features, I believe we have that. Is there anything specifically that you're missing?

**Comment by hishamco** [comment]
I made it unclear on the title, what I need to do is check the features without touching the UI tests. I presume this is a normal flow, or are you using TDD?

**Comment by hishamco** [comment]
One more thing how can I run the UI tests from within the repo? is there any integration to VS Testing Tools or I should use CLI instead?

**Comment by Piedone** [comment]
What do you mean by "check"? I really don't understand what you're looking for, sorry. If you want to try out the features, just add the NuGet packages to a standard OC app.

You need a solution for the tests, for which I recommend https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions.
