### ISSUE TITLE
Don't rely on relative paths (OSOE-804)

### ISSUE THREAD

**Issue by hishamco** [Lombiq/Hosting-Tenants#111]
I just noticed that this repo and other Lombiq repositories rely on different local repositories such as Helpful Libraries & Extensions .. etc. If this is the case we might need to use the path from cloned repositories instead of using local paths such as "Libraries" or "tests"

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-804)

**Comment by Piedone** [comment]
You have two options to use these modules:

- From NuGet as packages. Then, there are no paths to worry about, and all dependencies will be pulled from NuGet too.
- From source. Then, you also have to add their dependencies in source form.

Are you looking for a combination of the two, where you use these modules from source, but their dependencies are loaded from NuGet? We won't be able to support that.

**Comment by hishamco** [comment]
> From NuGet as packages. Then, there are no paths to worry about, and all dependencies will be pulled from NuGet too.

Right

> From source. Then, you also have to add their dependencies in source form.

Maybe I need to use git with submodules, If yes we might need to add it to README.md

**Comment by Piedone** [comment]
The recommended way for submodules is using https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions, what is linked from the Readme and that has documentation on submodules.

**Comment by hishamco** [comment]
Thanks
