### ISSUE TITLE
Lombiq.Hosting.Tenants.Management.HideRecipesFromSetup: Should this work on the Tenants->Create Tenant page? (OSOE-586)

### ISSUE THREAD

**Issue by ericrrichards** [Lombiq/Hosting-Tenants#51]
I have tried to setup the Lombiq.Hosting.Tenants.Management.HideRecipesFromSetup feature to exclude the Blog, Agency, and Coming Soon setup recipes as options for creating a new tenant.

`builder.HideRecipesByTagsFromSetup("blog", "agency", "comingsoon");`

I expected that this would remove these recipes as options that could be selected when creating a new tenant, if I am in the root or default tenant of a multi-tenant OrchardCore application, and I go to **Admin -> Configuration -> Tenants** and click the **Add Tenant** button.
But I am still seeing those options available.
![image](https://user-images.githubusercontent.com/2787661/223464392-9f90a1ab-78e7-48dc-8614-b54e48f6a86f.png)

I looked at the source of the OrchardCore.Tenants.Controller.AdminController code, and it doesn't look like that area uses an ISetupService instance to get setup recipes, but rather it collects them with RecipeHarvesters directly. So the wrapped version that this feature provides wouldn't be used there.

How is this supposed to be used?

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-586)

**Comment by Piedone** [comment]
The feature only hides the selected recipes from the setup screen, not the tenant management screen.

**Comment by Piedone** [comment]
From the thumbs up I suppose this answered your question, then.
