### ISSUE TITLE
IdleShutdownTask Feedback (OSOE-625)

### ISSUE THREAD

**Issue by jtkech** [Lombiq/Hosting-Tenants#57]
Because I had a chat with @Psichorex about the `IdleShutdownTask` I took a look at the code

https://github.com/Lombiq/Hosting-Tenants/blob/9dd77323d3b5bdd74ab5fedf9bb2c69ecfd79c9d/Lombiq.Hosting.Tenants.IdleTenantManagement/Services/IdleShutdownTask.cs#L58-L59

When we release a tenant on inactivity we don't want to signal it to other instances in a distributed env (e.g. if `OC.Tenants.Distributed` and `OC.RedisCache` are enabled), this because we have released the tenant on inactivity, not because it has changed. To do so you need to set to false the `eventSource` parameter.

     _shellHost.ReleaseShellContextAsync(_shellSettings, eventSource: false);

---

https://github.com/Lombiq/Hosting-Tenants/blob/9dd77323d3b5bdd74ab5fedf9bb2c69ecfd79c9d/Lombiq.Hosting.Tenants.IdleTenantManagement/Services/IdleShutdownTask.cs#L61-L68

No need to call `SaveSettingsAsync()` as it is done by `UpdateShellSettingsAsync()`, then as I understood we could have just call `ReloadShellContextAsync()`, but normally I think we don't need this (see below).

---

https://github.com/Lombiq/Hosting-Tenants/blob/9dd77323d3b5bdd74ab5fedf9bb2c69ecfd79c9d/Lombiq.Hosting.Tenants.IdleTenantManagement/Services/IdleShutdownTask.cs#L35-L54

`ReleaseShellContextAsync()` just releases the shell and remove the context and settings from the related shell host dictionaries, this without any database accesses, so normally it should not fail.

So normally all the above code could be replaced by only one line.

     return _shellHost.ReleaseShellContextAsync(_shellSettings, eventSource: false);

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-625)

**Comment by Piedone** [comment]
Thank you for these tips, JT! I think this might actually be a memory leak we're seeing.

**Comment by Psichorex** [comment]
Noted your comments and I soon will be addressing this aswell.

**Comment by jtkech** [comment]
> I think this might actually be a memory leak we're seeing.

Yes this is what we discussed on Skipe, but I don't see how releasing shells could be a source of leaks (knowing that the GC doesn't behave the same in dev/debug mode), unless if something else was wrong, for example releasing all shells by caling `ReleaseAllShellContextsAsync()` whose result would be that any tenant would have to be rebuilt on any subsequent request.

**Comment by Psichorex** [comment]
@jtkech Hi JT! Good to have you here aswell :)
This is my fully reworked code atm:
![image](https://github.com/Lombiq/Hosting-Tenants/assets/92299130/fb88b695-98d0-48b6-86df-1fc94bcbcf6f)

I added the `eventsource: false` parameter and I reworked the whole of it pretty much.
We are going to do a deploy with branch `NEST-361-dev-repro` and see if Azure is still facing memory leaks.

**Comment by Psichorex** [comment]
I have actually opted for using the serviceProvider:
![image](https://github.com/Lombiq/Hosting-Tenants/assets/92299130/fcb6301f-f32e-4091-ba60-080424799065)

**Comment by Piedone** [comment]
Addressed in https://github.com/Lombiq/Hosting-Tenants/pull/50.
