### ISSUE TITLE
Standardize feature names with the non-hyphenated "Lombiq Hosting - Tenants" prefix (OSOE-697)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Hosting-Tenants#90]
Some of the features currently use a hyphen in their name after "Lombiq Hosting - Tenants" (e.g. Lombiq Hosting - Tenants - Email Quota Management), some (most) not (e.g. Lombiq Hosting - Tenants Admin Login). Standardize this with the non-hyphenated version.

Change these texts everywhere, including, but not necessarily limited to, the UI, Readmes, csprojs, manifests.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-697)

**Comment by Psichorex** [comment]
What should be the case when the hyphen is for extending the module name so that the feature name can be properly separated?
![image](https://github.com/Lombiq/Hosting-Tenants/assets/92299130/5f94f992-7669-4f98-9912-90b6dff615be)
